[workspace]
resolver = "2"
members = [
  "quicklog",
  "quicklog-clock",
  "quicklog-flush",
  "quicklog-macros",
]

[profile.release]
lto = "thin"

[profile.opt]
inherits = "release"
codegen-units = 1
lto = "fat"
