[package]
name = "quicklog"
version = "0.2.2"
# passing all test cases through trybuild
autotests = false
edition = "2021"

[lib]
name = "quicklog"
path = "src/lib.rs"

[[test]]
name = "ui"
path = "tests/ui.rs"

[[test]]
name = "derive"
path = "tests/derive/derive.rs"

[dependencies]
lazy_format = "2.0.0"
quicklog-clock = { path = "../quicklog-clock", version = "0.1.2", registry = "ghp-cargo-local" }
quicklog-flush = { path = "../quicklog-flush", version = "0.1.2", registry = "ghp-cargo-local" }
quicklog-macros = { path = "../quicklog-macros", version = "0.1.0", registry = "ghp-cargo-local" }
quanta = "0.11.1"
once_cell = "1.18.0"
chrono = { version = "0.4.26", default-features = false, features = ["clock"] }
rtrb = "0.2.3"
dyn-fmt = "0.4.0"

[dev-dependencies]
criterion = "0.4.0"
delog = "0.1.6"
tracing = "0.1.37"
tracing-appender = "0.2.2"
tracing-subscriber = "0.3.16"
recycle-box = { version = "0.2.0"}
trybuild = "1.0.85"

[[bench]]
name = "logger_benchmark"
harness = false

[[bench]]
name = "quicklog_benchmark"
harness = false

[badges]
maintenance = { status = "actively-developed" }
