[package]
name = "quicklog"
version = "0.1.22"
edition = "2021"

[lib]
name = "quicklog"
path = "src/lib.rs"

[dependencies]
lazy_format = "2.0.0"
regex = "1.7.1"
quicklog-clock = { path = "../quicklog-clock", version = "0.1.2", registry = "ghp-cargo-local" }
quicklog-flush = { path = "../quicklog-flush", version = "0.1.2", registry = "ghp-cargo-local" }
quanta = "0.11.1"
once_cell = "1.18.0"
cfg-if = "1.0.0"
paste = "1.0.9"
heapless = "0.7.16"
chrono = { version = "0.4.26", default-features = false, features = ["clock"] }

[dev-dependencies]
criterion = "0.4.0"
delog = "0.1.6"
tracing = "0.1.37"
tracing-appender = "0.2.2"
tracing-subscriber = "0.3.16"

[[bench]]
name = "logger_benchmark"
harness = false

[[bench]]
name = "quicklog_benchmark"
harness = false

[badges]
maintenance = { status = "actively-developed" }
