// This file was generated by `build.rs`, do not modify this file manually!

/// Sets max capacity (in items) of logging queue, can be set through env var `QUICKLOG_MAX_LOGGER_CAPACITY_ITEMS`.
pub const MAX_LOGGER_CAPACITY_ITEMS: usize = 1000000;

/// Sets max capacity (in bytes) of byte buffer used for serialization with `^` prefix in logging, can be set through `QUICKLOG_MAX_SERIALIZE_BUFFER_CAPACITY_BYTES`.
pub const MAX_SERIALIZE_BUFFER_CAPACITY_BYTES: usize = 1000000;
