// This file was generated by `build.rs`, do not modify this file manually!

/// Sets max capacity of logging queue, can be set through env var `QUICKLOG_MAX_LOGGER_CAPACITY`.
pub const MAX_LOGGER_CAPACITY: usize = 1048576;

/// Sets max capacity of byte buffer used for serialization in logging, can be set through `QUICKLOG_MAX_SERIALIZE_BUFFER_CAPACITY`.
pub const MAX_SERIALIZE_BUFFER_CAPACITY: usize = 1000000;
